---

- name: host capacity
  hosts: "{{ host }}"
  gather_facts: yes
  tasks:
  - import_role:
      name: oracle_api_services
      tasks_from: host_capacity_insertion
    vars:
      task_key: "{{ ansible_hostname }}"
      task_rec_type: "LOAD_JSON"
      task_area: "HOST_CAPACITY"
      task_id: "{{ task_id }}"
      task_status: "SUCCESS"
      task_message: "Review Data in Body"
      standard_task_id: "{{ standard_task_id }}"
